from __future__ import annotations

from dataclasses import replace

import numpy as np

from motor_sim.core.builder import ModelBuilder



def test_multicylinder_build_and_rhs_runs(cfg):
    base = cfg.user_cylinders[0]
    cyl2 = replace(
        base,
        name=f"{base.name}_2",
        crank_angle_offset_deg=base.crank_angle_offset_deg + 360.0,
        notes="autogenerated test cylinder",
    )
    cfg2 = replace(
        cfg,
        user_cylinders=[base, cyl2],
        active_user_cylinder=cyl2.name,
    )

    S, ctx, model, t_span, y0 = ModelBuilder(cfg2).build()
    dy = model.rhs(t_span[0], y0.copy())

    assert len(ctx.cylinders) == 2
    assert ctx.cylinder.name == cyl2.name
    assert len(S.names) == 5 + 6 * 2
    assert y0.shape == (17,)
    assert dy.shape == y0.shape
    assert np.all(np.isfinite(dy))

    for cyl in ctx.cylinders:
        assert f"m__{cyl.name}" in S.idx
        assert f"T__{cyl.name}" in S.idx
        assert f"{cyl.name}__p_cyl_pa" in ctx.signals
